# Generated by Django 6.0.3 on 2026-05-13 17:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pomodoro', '0002_sesionestudio_delete_project'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionPomodoro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('focus_min', models.IntegerField(default=25)),
                ('focus_seg', models.IntegerField(default=0)),
                ('descanso_corto_min', models.IntegerField(default=5)),
                ('descanso_corto_seg', models.IntegerField(default=0)),
                ('descanso_largo_min', models.IntegerField(default=15)),
                ('descanso_largo_seg', models.IntegerField(default=0)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
